afet-yonetim-sistemi/ays-fe-institution

src/pages/assignments/Actions/CreateAssignment.tsx, src/pages/assignments/Actions/EditAssignment.tsx
Character delimitation has been changed
closes #103 
=> fix: character delimitation has been changed

src/pages/admins/list.tsx, src/pages/assignments/AssignmentList.tsx, src/pages/users/list.tsx
Atamalar Sayfasında Sayfa Başına Görüntülenme Sayısı Değiştirme Hataları
Closes #106 
@kevseroz @deniizeynep
=> fix: set pageSizeOptions as 10

src/pages/assignments/Actions/CreateAssignment.tsx, src/pages/assignments/Actions/EditAssignment.tsx
Atama Ekleme/Güncelleme Ekranındaki Koordinatların Kullanıcıya Gösterilmemesi
Closes #92
@kevseroz @deniizeynep
=> feature: hide location details

package-lock.json, package.json
This PR will fix dependabot alerts and vulnerabilities
If this pull request is related to any GitHub issue, please mention it here with the appropriate issue number.
@deniizeynep @kevseroz
=> fix: dependabot alerts and vulnerabilities

src/pages/assignments/Actions/CreateAssignment.tsx, src/pages/assignments/Actions/EditAssignment.tsx, src/pages/users/Actions/CreateUser.tsx
fix: accepting special characters for firstName and lastName inputs
closes #112 
=> fix: accepting special characters for firstName and lastName inputs

src/pages/assignments/Actions/CreateAssignment.tsx, src/pages/assignments/Actions/EditAssignment.tsx, src/pages/users/Actions/CreateUser.tsx
fix: phone number input error
closes #113 
=> fix: phone number input error

public/locales/tr/common.json, src/pages/users/Actions/ShowUser.tsx, src/pages/users/list.tsx
The user show page has been updated
closes  #118 
=> The user show page has been updated

public/locales/tr/common.json, src/pages/users/Actions/ShowUser.tsx, src/pages/users/list.tsx
The Institution area has been removed
closes #117 
=> The Institution area has been removed

src/pages/users/UserFilterForm.tsx, src/pages/users/list.tsx, src/providers/rest-data-provider/index.ts
Server taraflı sortlama işlemi
Related to [AYS-13](https://afetyonetimsistemi.atlassian.net/browse/AYS-13)
Please provide screenshots of any changes made, if applicable.
@kevseroz  @deniizeynep 
[AYS-13]: https://afetyonetimsistemi.atlassian.net/browse/AYS-13?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AYS-13 | Add server-side sorting to UserList component

src/pages/users/list.tsx
Please provide screenshots of any changes made, if applicable.
Please assign relevant reviewers to this pull request. Reviewers may be maintainers or experienced contributors who can provide valuable feedback.
=> AYS-185 | Reactivated: Preview modal reactivated on the user listing page after creating a user.

src/pages/users/Actions/ShowUser.tsx, src/pages/users/list.tsx
Corrected the user deletion action in the user details section on the user listing screen. And the user deletion action on the user listing page is working properly.
AYS-216
Please assign relevant reviewers to this pull request. Reviewers may be maintainers or experienced contributors who can provide valuable feedback.
=> AYS-216 | Fixed: Corrected the user deletion action in the user details section on the user listing screen.

src/pages/users/Actions/EditUser.tsx
Please provide a brief description of the changes made in this pull request.
If this pull request is related to any GitHub issue, please mention it here with the appropriate issue number.
Please provide screenshots of any changes made, if applicable.
Please assign relevant reviewers to this pull request. Reviewers may be maintainers or experienced contributors who can provide valuable feedback.
=> fix: add margin top for test automation.

package-lock.json, package.json, src/app/(private)/dashboard/page.tsx, src/app/(private)/layout.tsx, src/app/layout.tsx, src/components/dashboard/language-toggle.tsx, src/components/dashboard/menu.tsx, src/components/dashboard/mode-toggle.tsx, src/components/dashboard/navbar.tsx, src/components/dashboard/sidenav.tsx, src/components/theme-provider.tsx, src/components/ui/dropdown-menu.tsx, src/components/ui/select.tsx, src/components/ui/sheet.tsx, src/i18n/index.ts, src/i18n/locales/en.json, src/i18n/locales/tr.json
If this pull request is related to any GitHub issue, please mention it here with the appropriate issue number.
=> AYS-235 | Creating layouts for private pages

package-lock.json, package.json, src/app/(public)/login/page.tsx, src/components/dashboard/navbar.tsx, src/components/ui/avatar.tsx, src/configs/axiosConfig.ts, src/i18n/locales/en.json, src/i18n/locales/tr.json, src/lib/helpers.tsx, src/modules/auth/authSlice.ts, src/modules/auth/service.ts
Please provide a brief description of the changes made in this pull request.
If this pull request is related to any GitHub issue, please mention it here with the appropriate issue number.
Please provide screenshots of any changes made, if applicable.
Please assign relevant reviewers to this pull request. Reviewers may be maintainers or experienced contributors who can provide valuable feedback.
=> feat: handle logout and user menu

src/components/dashboard/menu.tsx
added loading spinner for while fetching APIversion information, fixed the string, cached the apiversion in localstorage as requested in jira ticket
=> AYS-256 fixed according to ticket comments

CONTRIBUTING.md
- Added Development Standards to Contributing.md
- …
=> AYS-311 | Add Development Standards to CONTRIBUTING.md

src/app/(private)/admin-registration-applications/[id]/page.tsx
- fixed the updatedAt value bug …
=> AYS-249 | fixed the updatedAt value bug

src/app/(private)/admin-registration-applications/[id]/page.tsx
=> fix: hotfix for phone number.

.github/dependabot.yml, .github/workflows/application-health-checker.yml, .github/workflows/pull-request-checker.yml, README.md
- Assignees have been added if necessary.
- No specific actions are required in the Labels and Associations …
=> AYS-355 | GitHub Actions Have Been Integrated as `pull-request-checker` and `application-health-checker`

src/components/dataTable/dataTableSearchField.tsx
- Add regex for fixed Invalid Seating Count (without - ,+ ,e) …
=> AYS-361 | fixed Invalid Seating Count (without - ,+ ,e)

src/app/hocs/isAuth.tsx
=> AYS-354 | fix permission issue

src/app/(private)/emergency-evacuation-applications/page.tsx
- Add Refresh Button to Emergency Evacuation Applications Page
- Default reviewers have been assigned to this …
=> AYS-360 | Add Refresh Button to Emergency Evacuation Applications Page

package-lock.json, package.json, src/app/(private)/admin-registration-applications/[id]/page.tsx, src/components/ui/dialog.tsx, src/i18n/locales/en.json, src/i18n/locales/tr.json
- Add reject and approve buttons to admin registration applications details page
- Default reviewers have been …
=> AYS-82 & AYS-81 | Add reject and approve buttons to admin registration applications details page

src/modules/emergencyEvacuationApplications/constants/status.ts
=> AYS-398 | delete inProgress status for requirements.

src/app/(private)/admin-registration-applications/[id]/page.tsx
- add auth check to ARA detail page …
=> AYS-384 | add auth check to ARA detail page

src/app/(private)/layout.tsx, src/configs/axiosConfig.ts
=> AYS-401 | fix(auth): Prevent requests without token, redirect to login

src/app/(private)/admin-registration-applications/[id]/page.tsx, src/components/ui/button.tsx, src/i18n/locales/en.json, src/i18n/locales/tr.json, src/modules/adminRegistrationApplications/components/dialog.tsx, src/modules/adminRegistrationApplications/service.ts
- Added API connections for Approver and Reject dialog
- Added Textarea for rejectReason
- Edited dialogs for reusable component
- Necessary documentation has been added or existing documentation …
=> AYS 81 & AYS 82 | Added API connections for approve and reject dialogs. 

src/app/(public)/login/page.tsx
- Updated Login Page Password Min Char Count to 6
- …
=> AYS-422 | Update Login Page Password Min Char Count

src/i18n/locales/en.json, src/i18n/locales/tr.json
- Menu names refactored.
- Assignees have been added …
=> AYS-445 | Menu names refactored

src/app/(private)/admin-registration-applications/[id]/page.tsx, src/i18n/locales/en.json, src/i18n/locales/tr.json, src/lib/providers.tsx
- Add Copy Link Button to Admin Registration Applications Details page
- Default reviewers have been assigned to …
=> AYS-408 | Add Register Completion Copy Link Button to ARA Details Page

package-lock.json, src/app/(private)/emergency-evacuation-applications/[id]/page.tsx
- The Reference Number on the Emergency Evacuation Application Details page is formatted using the Reference Number function..
- Necessary documentation has been added or existing documentation has …
=> AYS-447 | Correcting the Reference Number on the 'Emergency Evacuation Application Details' Screen

src/app/(private)/admin-registration-applications/page.tsx, src/middleware.ts
- fix 404 error in admin registration applications listing page, also hide the pre-application button from 
- …
=> AYS-406 | fix 404 error in admin registration applications listing page

src/app/(private)/admin-registration-applications/[id]/page.tsx
- add permission check to admin registration details page for reject and approve buttons
- Default reviewers have …
=> AYS-439 | add permission check for buttons in ara details 

src/app/(private)/roles/[id]/page.tsx
=> AYS-321 | remove update and delete buttons if the role is already deleted

src/app/(private)/roles/[id]/page.tsx, src/lib/handleApiError.ts
- bugfix role name validation and stop canceling changes if its not saved
- Default reviewers have been assigned …
=> AYS-301 | bugfix role name validation

src/app/(public)/layout.tsx
- change layout style for language and theme selection …
=> AYS-78 | change layout style for language and theme selection

src/i18n/index.ts
- change default language to english
- [] **Local Testing:**
- [] **Reviewers and Assignees:**
- Default …
=> AYS-538 | change default language to english

package.json, src/app/(private)/roles/[id]/page.tsx, src/i18n/locales/en.json, src/i18n/locales/tr.json, src/modules/roles/service.ts
- [ x] Feature addition
-  Role aktifleştirme ve Pasifleştirme işlemini gerçekleştirmektedir.
- https://afetyonetimsistemi.atlassian.net/browse/AYS-496
- https://afetyonetimsistemi.atlassian.net/browse/AYS-497
- [x ] **Title and Branch Naming Conventions:**
- [ x] **Local Testing:**
- [x ] **Code Quality:** …
=> AYS-496 & AYS-497 | Role activate and passivate

src/i18n/locales/tr.json
- [ x] Other (refactor)
- Fazla '.' noktayı kaldırdım.
- [ x] **Title and Branch Naming Conventions:**
- [x ] **Local Testing:**
- [x ] **Code Quality:**
- Necessary documentation has been added or …
=> AYS-497 | Remove extra dot

src/constants/regex.ts, src/i18n/locales/en.json, src/i18n/locales/tr.json, src/modules/adminRegistrationApplications/constants/formValidationSchema.ts, src/modules/login/constants/formValidationSchema.ts, src/modules/password/constants/formValidationSchema.ts
- changed validations for email and pw
- Assignees …
=> AYS-351-352 | fix descriptions, validations

src/app/(private)/admin-registration-applications/page.tsx, src/app/(private)/emergency-evacuation-applications/page.tsx, src/app/(private)/roles/page.tsx, src/app/(private)/users/page.tsx, src/components/ui/filter-input.tsx, src/constants/menuItems.ts, src/hooks/useSort.ts, src/i18n/locales/en.json, src/i18n/locales/tr.json, src/lib/getSortState.ts, src/modules/adminRegistrationApplications/components/columns.tsx, src/modules/adminRegistrationApplications/constants/types.ts, src/modules/adminRegistrationApplications/service.ts, src/modules/emergencyEvacuationApplications/components/columns.tsx, src/modules/emergencyEvacuationApplications/constants/types.ts, src/modules/emergencyEvacuationApplications/service.ts, src/modules/roles/components/columns.tsx, src/modules/roles/constants/types.ts, src/modules/roles/service.ts, src/modules/users/components/columns.tsx, src/modules/users/constants/statuses.ts, src/modules/users/constants/types.ts, src/modules/users/service.ts
- Add multiple sorting functionality, develop the user listing page,
- Default reviewers have been assigned to …
=> AYS-322 & AYS-457 | User Listing Page

src/configs/routes.ts
=> AYS-322 | Restrict User Listing Page 

src/app/(private)/roles/create-role/page.tsx, src/app/(private)/roles/page.tsx, src/configs/routes.ts, src/i18n/locales/en.json, src/i18n/locales/tr.json, src/lib/nameboxValidation.ts, src/modules/adminRegistrationApplications/constants/formValidationSchema.ts, src/modules/roles/constants/formValidationSchema.ts, src/modules/roles/service.ts
- Create Role Page
- Assignees have been added if …
=> AYS-302 | Create Role Page

src/app/(private)/admin-registration-applications/[id]/page.tsx, src/app/(private)/admin-registration-applications/pre-application/page.tsx, src/app/(private)/emergency-evacuation-applications/[id]/page.tsx, src/app/(private)/emergency-evacuation-applications/page.tsx, src/app/(private)/roles/[id]/page.tsx, src/app/(private)/roles/create-role/page.tsx, src/app/(private)/roles/page.tsx, src/app/(private)/users/[id]/page.tsx, src/app/(private)/users/page.tsx
- fixed
- Assignees have been added if necessary.
- …
=> AYS-619 | Language change triggers unnecessary backend calls

src/app/(private)/roles/[id]/page.tsx, src/app/(private)/users/[id]/page.tsx, src/i18n/locales/en.json, src/i18n/locales/tr.json, src/modules/users/service.ts
- User Activation Functionality …
=> AYS-499 | User Activation Functionality

src/app/(private)/users/[id]/page.tsx, src/i18n/locales/en.json, src/i18n/locales/tr.json, src/modules/users/service.ts
- User Deactivate Functionality …
=> AYS-498 | User Deactivate Functionality

src/components/ui/filter-input.tsx
…tcuts
- Accept Copy Paste shortcuts in num filter inputs …
=> AYS-605 | Accept Copy Paste shortcuts in num filter inputs

src/modules/adminRegistrationApplications/constants/formValidationSchema.ts
- fix pre application Required Validation Error Message …
=> AYS-612 | fix pre application Required Validation Error Message

package-lock.json, package.json, src/app/(private)/admin-registration-applications/page.tsx, src/app/(private)/emergency-evacuation-applications/page.tsx, src/app/(private)/roles/page.tsx, src/app/(private)/users/page.tsx
- fix fetching twice at initial rendering in listing pages …
=> AYS-595 | Fix Fetching Twice

src/app/(private)/users/[id]/page.tsx, src/i18n/locales/en.json, src/i18n/locales/tr.json, src/modules/users/service.ts
=> AYS-325 | User Deletion Functionality

src/modules/emergencyEvacuationApplications/components/columns.tsx
=> AYS-376 | Update fields in emergency evacuation applications page

src/app/(private)/users/page.tsx
=> AYS-627 | Remove Country Code Filter

src/app/(private)/admin-registration-applications/page.tsx
- change debounce timer to 0.5seconds
- Assignees …
=> AYS-595 | Change Debounce Timer to 0.5 seconds

src/i18n/locales/en.json
- Assignees have been added if necessary.
- Closes …
=> AYS-323 | fix no roles info message

src/app/(private)/users/create-user/page.tsx, src/modules/users/constants/formValidationSchema.ts
- Add user creation validations …
=> AYS-326 | user creation validations

src/app/(private)/users/[id]/page.tsx
- hide active/passive button for not_verfied
- …
=> AYS-499 | Hide activate button for not verified 

src/constants/formValidationSchema.ts, src/modules/adminRegistrationApplications/constants/formValidationSchema.ts, src/modules/login/constants/formValidationSchema.ts, src/modules/password/constants/formValidationSchema.ts
- Changed PW length validation …
=> AYS-615 | Change Password Length Validation

src/modules/adminRegistrationApplications/constants/formValidationSchema.ts
- add max length validation for reason in pre pregistration page
- Default reviewers have been assigned to this …
=> AYS-697 | add max length validation for reason in pre pregistration page

src/app/(private)/admin-registration-applications/page.tsx, src/app/(private)/emergency-evacuation-applications/page.tsx, src/app/(private)/roles/page.tsx, src/app/(private)/users/page.tsx, src/components/ui/data-table.tsx
=> AYS-581 | add enable rowclick logic

src/app/(private)/users/[id]/page.tsx, src/app/(private)/users/create-user/page.tsx, src/hooks/useFetchRoleSummary.ts, src/i18n/locales/en.json, src/i18n/locales/tr.json, src/modules/users/constants/formValidationSchema.ts, src/modules/users/constants/types.ts, src/modules/users/service.ts
- Add User update functionality …
=> AYS-324 | User Update Functionality

PULL_REQUEST_TEMPLATE.md, src/app/(private)/admin-registration-applications/page.tsx, src/app/(private)/emergency-evacuation-applications/page.tsx, src/app/(private)/roles/page.tsx, src/app/(private)/users/page.tsx, src/components/ui/filter-input.tsx, src/hooks/useDebouncedInputFilter.ts, src/hooks/useHandleFilterChange.ts
- Fixed Laggy filter input interractions
- Assignees …
=> AYS-584 | Fix Input Filter Lag 

src/i18n/locales/en.json, src/i18n/locales/tr.json
- Fix description
- The code does not contain any issues …
=> AYS-615 | Fix description

src/app/(private)/emergency-evacuation-applications/page.tsx, src/app/(private)/roles/page.tsx, src/app/(private)/users/page.tsx, src/common/types.ts, src/constants/filterValidationSchema.ts, src/i18n/locales/en.json, src/i18n/locales/tr.json, src/modules/adminRegistrationApplications/constants/formValidationSchema.ts, src/modules/login/constants/formValidationSchema.ts, src/modules/users/constants/formValidationSchema.ts
- add email length validations
- The code does not contain any …
=> AYS-662 | add email length validations

src/app/(private)/users/page.tsx
- Add line number length validation to user filtering
- The …
=> AYS-682 | Add line number length validation to user filtering

src/app/(private)/users/[id]/page.tsx
- hide update button for unverified users
- The code does not …
=> AYS-725 | hide update button for unverified users

src/app/(private)/users/[id]/page.tsx
=> AYS-726 | add switches to users' roles

src/app/(public)/layout.tsx
- fix page shifting in public pages when scrollbar is needed
- …
=> AYS-530 | Scrollbar Page Shifting Problem

src/app/(public)/layout.tsx, src/app/(public)/login/page.tsx, src/app/(public)/register-completion/[id]/page.tsx, src/components/password/CreatePasswordCard.tsx
- remove error toast and navbar from register completion page …
=> AYS-529 | remove error toast and navbar from register completion page

src/constants/menuItems.ts
- re ordered menu items
- The code does not contain any issues …
=> AYS-728 | order menu items

src/app/(private)/admin-registration-applications/[id]/page.tsx
- do not render if user info is empty in ARA detail page
- The …
=> AYS-730 | do not render if user info is empty

src/app/(private)/roles/create-role/page.tsx, src/i18n/locales/en.json, src/i18n/locales/tr.json
- add title to role create page
- The code does not contain …
=> AYS-731 | add title to role create page

src/app/(private)/admin-registration-applications/pre-application/page.tsx
- fix create button
- The code does not contain any issues …
=> AYS-729 | Fix create button

src/app/(private)/users/create-user/page.tsx, src/i18n/locales/en.json, src/i18n/locales/tr.json
=> AYS-732 | redesign create user page

src/app/(private)/roles/create-role/page.tsx
=> AYS-731 | Fix role create button

src/app/(public)/register-completion/[id]/page.tsx
- Disable country code field in admin registration completion screen
- The code has been reviewed to ensure its …
=> AYS-643 | Disable country code field in admin registration completion screen

package-lock.json, package.json, src/app/(private)/users/[id]/page.tsx, src/app/(private)/users/create-user/page.tsx, src/app/(public)/register-completion/[id]/page.tsx, src/app/globals.css, src/components/ui/input.tsx, src/components/ui/phone-input.tsx, src/constants/formValidationSchema.ts, src/i18n/locales/tr.json, src/modules/users/constants/formValidationSchema.ts
- Replace phone number component
- The code does not contain …
=> AYS-519 | Fix phone number issues in forms

src/app/(private)/users/create-user/page.tsx, src/app/(public)/register-completion/[id]/page.tsx, src/components/PhoneNumberField.tsx
- fix sonarqube quality gate code duplication issue
- The code …
=> AYS-519 | fix sonarqube quality gate code duplication issue

src/app/(private)/emergency-evacuation-applications/page.tsx, src/app/(private)/roles/page.tsx, src/app/(private)/users/page.tsx, src/components/ui/filter-input.tsx, src/components/ui/multi-select-dropdown.tsx
- This PR updates the validation error display for filter fields. Previously, validation errors appeared as toast messages in the bottom-right corner. Now, errors are displayed inline within the respective input fields, ensuring a more user-friendly and accessible experience.
- I have tested my changes locally on my …
=> AYS-632 | Updating Validation Error Display to Match Form Field Style

src/app/(private)/users/[id]/page.tsx
=> AYS-324 | Perfomance Improvement in User Update Role Selection

src/app/(private)/users/[id]/page.tsx
=> AYS-519 | Fix Line Number Empty Issue in User Updating

src/app/(private)/emergency-evacuation-applications/page.tsx, src/app/(private)/users/page.tsx, src/components/ui/filter-input.tsx
- Removed the increment/decrement controls from numeric filtering fields where unnecessary by introducing a hideNumberSpinner prop for better control.
- The code is formatted according to the …
=> AYS-687 | Remove Increase Decrease Option in Numeric Filtering Fields 

LICENSE.md, SECURITY.md
- Update License and Security Files with iletisim@afetyonetimsistemi.org
- The code has been reviewed to ensure …
=> AYS-781 | Update License and Security Files

.github/workflows/pull-request-checker.yml
- Update PR Checker so edits in PR does not rerun the build
- …
=> AYS-791 | Update PR Checker

src/app/(private)/roles/[id]/page.tsx, src/app/(private)/roles/create-role/page.tsx, src/app/(private)/users/[id]/page.tsx, src/app/(private)/users/create-user/page.tsx, src/hooks/useFetchRoleSummary.ts
- Add Loading Indicator to Permission and User Role Fetching
- …
=> AYS-771 | Add Loading Indicator to Permission and User Role Fetching

src/i18n/locales/en.json, src/i18n/locales/tr.json
- Fix column header text for is in person
- The code does not …
=> AYS-452 | Fix column header text for is in person

src/components/ui/data-table-sort.tsx
- fixed alignment of sortable column header names
- The code …
=> AYS-796 | alignment of sortable column header names

src/app/(private)/emergency-evacuation-applications/[id]/page.tsx, src/i18n/locales/en.json, src/i18n/locales/tr.json, src/modules/emergencyEvacuationApplications/constants/formValidationSchema.ts
- Added confirmation dialog when updating an emergency evacuation application to COMPLETED or CANCELLED.
- The …
=> AYS-300 | Add confirmation modal

src/i18n/locales/en.json, src/i18n/locales/tr.json
- Implemented the requested feature and updated the necessary modules accordingly.
- The code has been reviewed to …
=> AYS-809 | Texts of Emergency Evacuation Application Statuses Have Been Improved

next.config.mjs, src/app/(private)/admin-registration-applications/page.tsx, src/app/(private)/emergency-evacuation-applications/page.tsx, src/app/(private)/roles/page.tsx, src/app/(private)/users/page.tsx, src/i18n/locales/en.json, src/i18n/locales/tr.json, src/lib/getFilterErrors.ts
- Fix multiple fetch request in initial table render
- The …
=> AYS-779 | multiple fetch request in initial table render

package-lock.json, package.json, src/constants/formValidationSchema.ts
- changed phone number validations to use google-phonenumber
- …
=> AYS-741 | change phonenumber validation

src/app/(private)/emergency-evacuation-applications/[id]/page.tsx
- changed eaa detail update save button disable status logic
- …
=> AYS-821 | change eaa update save button disable status logic

src/components/ui/data-table-sort.tsx
- Fixed sortable column alignment
- The code does not contain …
=> AYS-796 | Fix sortable column alignment

src/app/(private)/roles/create-role/page.tsx
- changed styling of role name in role create page
- The code …
=> AYS-819 | change styling of role name in role create page

src/app/(private)/users/page.tsx
- Phone Number Filtering Max Length Validation Updated
- The …
=> AYS-833 | Phone Number Filtering Max Length Validation Update

src/app/(private)/roles/[id]/page.tsx
- fixed localization of permissions in role details page
- The …
=> AYS-835 | Role details page permissions localization fix

src/components/ui/filter-input.tsx
- Allow filtering by seat count with values starting with 0 (e.g., 0010 → 10)
- The code has been reviewed to …
=> AYS-617 | Allow filtering by seat count with values starting with 0 (e.g., 0010 → 10)

package-lock.json, src/app/(private)/emergency-evacuation-applications/[id]/page.tsx, src/components/ui/status.tsx
- Add colorful eea status to eaa detail page
- The code does …
=> AYS-810 | Reflecting the Colored Visualization of Emergency Application Statuses on the Detail and Update Pages

src/app/(private)/roles/page.tsx, src/common/types.ts, src/constants/filterValidationSchema.ts, tsconfig.json
-  Update validations for role name in filter field
- The code …
=> AYS-744 | Update validations for role name in filter field

src/app/(private)/users/page.tsx
- Updated validation rules for name filters
- The code does …
=> AYS-641 | Update validation rules for name filters

src/modules/roles/constants/formValidationSchema.ts
- Updated Role Name Form Validations
- The code does not …
=> AYS-743 | Update Role Name Form Validations

src/app/layout.tsx
- Used dynamic metadata generation
- The code does not contain …
=> AYS-738 | Use dynamic metadata generation

src/lib/strictValidation.ts, src/modules/adminRegistrationApplications/constants/formValidationSchema.ts, src/modules/users/constants/formValidationSchema.ts
- Updated name form field validations according to documentation rules
- The code has been reviewed to ensure its …
=> AYS-534 | Update name form field validations

package-lock.json, package.json
- Updated packages
- The code does not contain any issues …
=> AYS-869 | Fix build warnings

src/components/ui/dialog.tsx, src/contexts/validateRouteProvider.tsx, src/i18n/locales/en.json, src/i18n/locales/tr.json, src/lib/showToast.ts
- show pop up about session expired information for 401 errors …
=> AYS-878 | show pop up about session expired for 401 errors

src/app/(public)/login/page.tsx
- Similar to createPassword and registerCompletion, the Card width has been adjusted and the description has been centered.
- The code is formatted according to the project's coding guidelines …
=> AYS-906 |  Card Width Adjusted And Description Centered in Login Page

CODEOWNERS
=> `CODEOWNERS` File Has Been Updated
